//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductSys.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPStorage
    {
        public int ID { get; set; }
        public int ProductId { get; set; }
        public int StorageAmount { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
