//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductSys.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPOrder
    {
        public int ID { get; set; }
        public int ProductId { get; set; }
        public int BuyAmount { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public System.DateTime BuyDate { get; set; }
        public bool IsArrivaled { get; set; }
        public Nullable<System.DateTime> ArrivaledDate { get; set; }
        public string BuyPerson { get; set; }
        public string Notes { get; set; }
    }
}
