//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductSys.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StorageDbContext : DbContext
    {
        public StorageDbContext()
            : base("name=StorageDbContext")
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
            
        }
    
        public DbSet<EPStorage> EPStorages { get; set; }
        public DbSet<EPStorageCheck> EPStorageChecks { get; set; }
    }
}
